# This script is going to handle incoming events from the Redis queue.
# Once we receive an event, we need to parse it, and extract coin address/pair address.
# Then we check social media for mentions of the coin address/pair address.
# If we find a mention:
# We pass it through our models to get a sentiment score, and an engagement score prediction.
# For each coin/pair we are going to query the price to look for ATH time delta, ATH price gain, presence of a rug pull event.

# make a coin table
# so far we have:
# id - AUTOGENERATED
# event signature - DONE
# exchange - DONE
# creation_timestamp - DONE
# coin address - DONE
# pair address - DONE
# ATH time delta
# ATH price gain
# rugpull flag
# rugpull timestamp
# rugpull time delta

import redis
import argparse
import sys
from pathlib import Path
import yaml
import json
import os
import asyncio
import time
import requests
from solana.rpc.async_api import AsyncClient
from solders.signature import Signature
import db_utils

config_path = Path(__file__).parent / "config.yaml"
config = yaml.safe_load(config_path.read_text()) or {}

async def fetch_transaction_details(signature: str):
    async with AsyncClient(config["solana"]["rpc_http"]) as client:
        sig_obj = Signature.from_string(signature)
        resp = await client.get_transaction(
            sig_obj,
            encoding="jsonParsed",
            commitment="confirmed",
            max_supported_transaction_version=0
        )
        if resp.value is None:
            print(f"No transaction found for signature: {signature}")
            return None
        else:
            # write to a temp file
            with open("transaction.json", "w") as f:
                f.write(resp.to_json())
            # read into a dict
            with open("transaction.json", "r") as f:
                transaction_dict = json.load(f)
            # delete the temp file
            os.remove("transaction.json")
            return transaction_dict

async def find_coin_address(signature: str, exchange: str):
    try:
        transaction_dict = await fetch_transaction_details(signature)
    except Exception as e:
        print(f"Error fetching transaction details for {signature}: {e}")
        return None, None

    if transaction_dict is None:
        return None, None

    result = transaction_dict["result"]
    transaction = result["transaction"]
    message = transaction["message"]
    instructions = message["instructions"]

    for instruction in instructions:
        program_id = instruction["programId"]

        if program_id == "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8":
            accounts = instruction["accounts"]
            coin_address = accounts[8]
            pair_address = accounts[4]
            return coin_address, pair_address
        
        elif program_id == "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C":
            accounts = instruction["accounts"]
            token_mint_0 = accounts[4]
            token_mint_1 = accounts[5]
            coin_address = token_mint_1
            if token_mint_1 == "So11111111111111111111111111111111111111112":
                coin_address = token_mint_0
            pair_address = accounts[3]
            return coin_address, pair_address                

        elif program_id == "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK":
            accounts = instruction["accounts"]
            if len(accounts) == 13:
                token_mint_0 = accounts[3]
                token_mint_1 = accounts[4]
                coin_address = token_mint_1
                if token_mint_1 == "So11111111111111111111111111111111111111112":
                    coin_address = token_mint_0
                pair_address = accounts[2]
                return coin_address, pair_address

        elif program_id == "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P":
            accounts = instruction["accounts"]
            coin_address = accounts[2]
            pair_address = accounts[9]
            return coin_address, pair_address
        
        elif program_id == "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA":
            accounts = instruction["accounts"]
            coin_address = accounts[3]
            if coin_address == "So11111111111111111111111111111111111111112":
                coin_address = accounts[4]
            pair_address = accounts[0]
            return coin_address, pair_address

    return None, None

def get_coin_meta(coin_address: str):
    url = f"https://api.rugcheck.xyz/v1/tokens/{coin_address}/report"
    resp = requests.get(url)
    resp.raise_for_status()
    return resp.json()

async def handle_event(host: str, port: int, queue_name: str):
    """Connects to Redis and prints items from the specified queue."""
    try:
        r = redis.Redis(host=host, port=port, db=0, decode_responses=True)
        r.ping() # Check connection
        print(f"Successfully connected to Redis at {host}:{port}")
    except redis.exceptions.ConnectionError as e:
        print(f"Error connecting to Redis at {host}:{port}: {e}", file=sys.stderr)
        sys.exit(1)

    # initialize SQLite database and create coin_table if it doesn't exist
    db_utils.init_db()

    while True:
        try:
            # pop the first item from the queue
            item = r.lpop(queue_name)
            if item is None:
                time.sleep(10)
                continue

            # parse the item
            signature, exchange, creation_timestamp = item.split(",")

            # find coin/pair address based on exchange
            coin_address, pair_address = await find_coin_address(signature, exchange)

            if coin_address is None or pair_address is None:
                print(f"Error: could not find coin/pair address for {signature} on {exchange}")
                continue

            # get coin meta
            try:
                response = get_coin_meta(coin_address)
                if response is None:
                    print(f"Error: could not get coin meta for {coin_address}")
                    continue

                tokenMeta = response["tokenMeta"]
                creator = response["creator"]
                coin_name = tokenMeta["name"]
                coin_symbol = tokenMeta["symbol"]
                liquidity = response["totalMarketLiquidity"]
                price = response["price"]
                rug_bool = response["rugged"]

                if liquidity < 1000:
                    continue

                if rug_bool:
                    continue
            except Exception as e:
                print(f"Error: could not get coin meta for {coin_address}: {e}")
                continue

            # insert event into database
            row_id = db_utils.insert_coin_event(signature, exchange, creation_timestamp, coin_address, pair_address, coin_name, coin_symbol, creator, liquidity, price)
            if row_id is None:
                print(f"Warning: event {signature} may already exist or failed to insert into DB")

        except redis.exceptions.ResponseError as e:
            print(f"Error accessing queue '{queue_name}': {e}", file=sys.stderr)
            sys.exit(1)
        except Exception as e:
            print(f"An unexpected error occurred: {e}", file=sys.stderr)
            sys.exit(1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="View items in a Redis queue (list).")
    parser.add_argument("--queue_name", default = "solana_signatures", help="Name of the Redis queue (list) to view.")
    parser.add_argument("--host", default="localhost", help="Redis server host (default: localhost)")
    parser.add_argument("--port", type=int, default=6379, help="Redis server port (default: 6379)")

    args = parser.parse_args()

    asyncio.run(handle_event(args.host, args.port, args.queue_name))


